# Generated by Django 5.0.3 on 2024-03-29 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "size",
                    models.CharField(
                        choices=[
                            ("T", "Tiny"),
                            ("S", "Small"),
                            ("M", "Medium"),
                            ("L", "Large"),
                        ],
                        max_length=6,
                    ),
                ),
                ("friendliness", models.IntegerField()),
                ("trainability", models.IntegerField()),
                ("shedding_amount", models.IntegerField()),
                ("exercise_needs", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Dog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=64)),
                ("color", models.CharField(max_length=64)),
                ("favorite_food", models.CharField(max_length=256)),
                ("favorite_toy", models.CharField(max_length=256)),
            ],
        ),
        migrations.AddConstraint(
            model_name="breed",
            constraint=models.CheckConstraint(
                check=models.Q(("friendliness__gte", 1), ("friendliness__lte", 5)),
                name="friendliness_gte_1_lte_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="breed",
            constraint=models.CheckConstraint(
                check=models.Q(("trainability__gte", 1), ("trainability__lte", 5)),
                name="trainability_gte_1_lte_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="breed",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("shedding_amount__gte", 1), ("shedding_amount__lte", 5)
                ),
                name="shedding_amount_gte_1_lte_5",
            ),
        ),
        migrations.AddConstraint(
            model_name="breed",
            constraint=models.CheckConstraint(
                check=models.Q(("exercise_needs__gte", 1), ("exercise_needs__lte", 5)),
                name="exercise_needs_gte_1_lte_5",
            ),
        ),
        migrations.AddField(
            model_name="dog",
            name="breed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app.breed"
            ),
        ),
        migrations.AddConstraint(
            model_name="dog",
            constraint=models.CheckConstraint(
                check=models.Q(("age__gt", 0)), name="age_gt_1"
            ),
        ),
    ]
